
# per discussion in GH-#218, we aren't applying formatters to old code yet (to
# avoid merge conflicts).
# - most exclusions are specified in formtter-specific files (such as
#   clang-format's .clang-format-ignore file)
# - here we list the remaining files that should be excluded.
exclude: "^(\
src/python/pygrackle/grackle_defs.pxd\
|src/python/pygrackle/grackle_wrapper.pyx\
)"

ci:
    autofix_prs: false
    autoupdate_schedule: monthly

repos:

# there are some other useful hooks we could enable from here in the future
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-executables-have-shebangs

repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    # unlike most pre-commit tools, the version of this repository exactly
    # matches the version of clang-format
    rev: v18.1.3
    hooks:
    -   id: clang-format
        verbose: true
        types_or: [c++, c]
        args: ["-style=file", "--verbose"]

# settings adopted from yt
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks:
  - id: ruff-format
    types_or: [ python, pyi, jupyter ]
  - id: ruff
    types_or: [ python, pyi, jupyter ]
    args: [--fix, "--show-fixes"]

# uncomment the following, when we stop excluding cython files
# (settings adopted from yt)
#- repo: https://github.com/MarcoGorelli/cython-lint
#  rev: v0.16.2
#  hooks:
#  - id: cython-lint
#    args: [--no-pycodestyle]
